

name: Deno

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      # - name: Verify formatting
      #   run: deno fmt --check
      - name: sudo git clone "https://github.com/nityanand86876/converter1.git" && cd converter1
        run:  sudo git clone "https://github.com/nityanand86876/converter1.git"
      - name: firebase download
        run: sudo npm -g install "firebase-tools"
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      - name: deploy
        run: firebase deploy --token "$Env:NGROK_AUTH_TOKEN"
