name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Installing Firebase Tools.
      - run: npm -g install "firebase-tools"
      - name: Deploying it.
      - run: firebase deploy --token "${{ secrets.token }}"